"use client";

// String-key → Phosphor icon map. Kept in a client module (Phosphor icons are
// client components); the menu data (lib/nav/megaMenu.ts) stays pure/server-safe
// and only references these by key.
import {
  Bank,
  Briefcase,
  Buildings,
  ChartBar,
  ClipboardText,
  CreditCard,
  Diamond,
  Dna,
  Envelope,
  Handshake,
  Headset,
  Laptop,
  Lightning,
  MapTrifold,
  Money,
  Notebook,
  Robot,
  Rocket,
  ShieldCheck,
  Star,
  Target,
  TrendUp,
  UsersThree,
  Wallet,
  type Icon,
} from "@phosphor-icons/react";

export const menuIcons: Record<string, Icon> = {
  Bank,
  Briefcase,
  Buildings,
  ChartBar,
  ClipboardText,
  CreditCard,
  Diamond,
  Dna,
  Envelope,
  Handshake,
  Headset,
  Laptop,
  Lightning,
  MapTrifold,
  Money,
  Notebook,
  Robot,
  Rocket,
  ShieldCheck,
  Star,
  Target,
  TrendUp,
  UsersThree,
  Wallet,
};
