"use client";

// String-key → Phosphor icon map for the interior detail templates. Data files
// (lib/interior/*) stay server-safe and reference icons by key; the templates
// resolve them here. Duotone weight for feature/step tiles, matching the
// Spine detail-template reference.
import {
  ArrowsClockwise,
  Bank,
  Bell,
  Briefcase,
  Buildings,
  Cake,
  Check,
  ChartBar,
  ChartLineUp,
  ChatCircleText,
  ClipboardText,
  CreditCard,
  CurrencyCircleDollar,
  Diamond,
  Dna,
  Door,
  Envelope,
  FileText,
  FirstAidKit,
  FolderOpen,
  Gift,
  Globe,
  HandCoins,
  HandWaving,
  Handshake,
  Headset,
  Laptop,
  Lightbulb,
  Lightning,
  LockKeyOpen,
  MagnifyingGlass,
  MapPinLine,
  MapTrifold,
  Money,
  NotePencil,
  Notebook,
  Package,
  PenNib,
  Phone,
  Pill,
  PlugsConnected,
  Robot,
  RocketLaunch,
  Scales,
  ShieldCheck,
  Signature,
  Star,
  Target,
  TrendDown,
  TrendUp,
  Umbrella,
  UserCircle,
  UserPlus,
  UsersThree,
  Wallet,
  Warning,
  type Icon,
} from "@phosphor-icons/react";

export const interiorIcons: Record<string, Icon> = {
  ArrowsClockwise,
  Bank,
  Bell,
  Briefcase,
  Buildings,
  Cake,
  Check,
  ChartBar,
  ChartLineUp,
  ChatCircleText,
  ClipboardText,
  CreditCard,
  CurrencyCircleDollar,
  Diamond,
  Dna,
  Door,
  Envelope,
  FileText,
  FirstAidKit,
  FolderOpen,
  Gift,
  Globe,
  HandCoins,
  HandWaving,
  Handshake,
  Headset,
  Laptop,
  Lightbulb,
  Lightning,
  LockKeyOpen,
  MagnifyingGlass,
  MapPinLine,
  MapTrifold,
  Money,
  NotePencil,
  Notebook,
  Package,
  PenNib,
  Phone,
  Pill,
  PlugsConnected,
  Robot,
  RocketLaunch,
  Scales,
  ShieldCheck,
  Signature,
  Star,
  Target,
  TrendDown,
  TrendUp,
  Umbrella,
  UserCircle,
  UserPlus,
  UsersThree,
  Wallet,
  Warning,
};

export function InteriorIcon({
  name,
  size = 24,
  weight = "duotone",
  className,
  color,
}: {
  name: string;
  size?: number;
  weight?: "duotone" | "fill" | "bold" | "regular";
  className?: string;
  color?: string;
}) {
  const Cmp = interiorIcons[name] ?? Lightbulb;
  return <Cmp size={size} weight={weight} className={className} color={color} />;
}
